# Generated by Django 5.2.9 on 2025-12-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('available_hours_per_day', models.FloatField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(unique=True)),
                ('sap_tn', models.CharField(max_length=50)),
                ('sap_pl', models.CharField(blank=True, max_length=50, null=True)),
                ('dcc_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('demand_2024', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=0)),
                ('num_batches', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('step_name', models.CharField(max_length=200)),
                ('cycle_time_seconds', models.FloatField()),
                ('workers_required', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='api.machine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='api.product')),
            ],
            options={
                'db_table': 'process_steps',
                'ordering': ['product', 'step_number'],
                'unique_together': {('product', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50)),
                ('batch_num', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.machine')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.processstep')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.product')),
            ],
            options={
                'db_table': 'production_schedules',
                'ordering': ['start_time', 'machine'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='production__start_t_3309c4_idx'), models.Index(fields=['machine', 'start_time'], name='production__machine_ac7776_idx')],
            },
        ),
    ]
